version: 0.9.999.{build}
branches:
  only:
  - master
skip_commits:
  files:
    - '**/*.md'
    - '**/*.aip'
image: Visual Studio 2017
configuration: Release
platform:
  - x86
  - x64
build:
  verbosity: minimal
before_build:
- cmd: >-
    set "BUILD_COMMIT_VERSION=%APPVEYOR_BUILD_VERSION%-%APPVEYOR_REPO_COMMIT:~0,8%"

    set "BUILD_VERSION_COMMA=%APPVEYOR_BUILD_VERSION:.=,%"

    set "BUILD_ZIPFILE=%APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%_v%BUILD_COMMIT_VERSION%-%PLATFORM%.zip"
after_build:
- cmd: >-
    copy /Y "COPYING" "src\wufuc_setup_bat\COPYING.txt"

    cd "%APPVEYOR_BUILD_FOLDER%\src\wufuc_setup_bat"

    echo v%BUILD_COMMIT_VERSION%>version.txt

    for /R %%i in (*.txt) do unix2dos "%%i"

    for /R %%i in (*.bat) do unix2dos "%%i"

    7z a "%BUILD_ZIPFILE%" "..\wufuc_setup_bat"

    7z rn "%BUILD_ZIPFILE%" "wufuc_setup_bat" "%APPVEYOR_PROJECT_NAME%"
artifacts:
  - path: '*.zip'
